// content/home.js
// Static bilingual content and fallback data for app/page.js (extracted verbatim, Phase 5 structural refactor).

export const MEDIA_ITEMS_FALLBACK = [
  {
    src: "/img1.jpeg",
    captionAr: "مجمع ناصر الطبي - غزة",
    captionEn: "Nasser Medical Complex - Gaza",
    tag: "مستشفى",
    tagEn: "Hospital",
  },
  {
    src: "/img2.jpeg",
    captionAr: "جانب من حضور الطواقم الطبية في المؤتمر",
    captionEn: "Medical Staff Attendance at the Conference",
    tag: "فعاليات",
    tagEn: "Events",
  },
  {
    src: "/img3.jpeg",
    captionAr: "قاعة المحاضرات الرئيسية والافتتاح المعرفي",
    captionEn: "Main Lecture Hall and Opening Presentation",
    tag: "ورش",
    tagEn: "Workshops",
  },
  {
    src: "/img4.jpeg",
    captionAr: "تقديم الأوراق العلمية والبحوث الطبية",
    captionEn: "Presentation of Scientific Papers and Medical Research",
    tag: "جلسات",
    tagEn: "Sessions",
  },
  {
    src: "/img5.jpeg",
    captionAr: "المنصة الرئيسية وتكريم المشاركين",
    captionEn: "Main Stage and Honoring Participants",
    tag: "متحدثون",
    tagEn: "Speakers",
  },
  {
    src: "/img6.jpeg",
    captionAr: "تكريم الأطباء واللجان المنظمة للمؤتمر",
    captionEn: "Honoring Doctors and Organizing Committees",
    tag: "متحدثون",
    tagEn: "Speakers",
  },
  {
    src: "/img7.jpeg",
    captionAr: "مناقشات الأبحاث الطبية والبوسترات العلمية",
    captionEn: "Medical Research Discussions and Scientific Posters",
    tag: "جلسات",
    tagEn: "Sessions",
  },
  {
    src: "/img8.jpeg",
    captionAr: "كلمة الوفود والمنظمين في حفل الافتتاح",
    captionEn: "Speech by Delegations and Organizers at the Opening",
    tag: "فعاليات",
    tagEn: "Events",
  },
  {
    src: "/img9.jpeg",
    captionAr: "التجمع والنقاشات الجانبية للأطباء والوفود",
    captionEn: "Gathering and Side Discussions of Doctors and Delegations",
    tag: "فعاليات",
    tagEn: "Events",
  },
  {
    src: "/img10.jpeg",
    captionAr: "الصورة الجماعية الختامية للمؤتمر الطبي",
    captionEn: "Closing Group Photo of the Medical Conference",
    tag: "فعاليات",
    tagEn: "Events",
  },
];

export const TRANSLATIONS = {
  ar: {
    dir: "rtl",
    conferenceTitle: "المؤتمر الطبي الدولي الثاني عشر",
    conferenceSub: "للصمود والاستدامة في الطوارئ والاستجابة الإنسانية",
    btnReg: "قدم بحثك الآن",
    btnProg: "البرنامج العلمي",
    watchVideo: "شاهد الفيلم التعريفي",
    statsLbls: ["متحدث دولي", "جلسة علمية", "مشترك متوقع", "دولة مشاركة"],
    newsTitle: "أخبار المؤتمر",
    newsTicker: "أخبار",
    membersLbl: "رئيس اللجنة",
    expertiseLbl: "التخصصات",
    galleryTitle: "معرض الوسائط",
    gallerySub: "لقطات من فعاليات المؤتمر",
    leadersTitle: "قيادة المؤتمر",
    committeesTitle: "لجان المؤتمر",
    presidentQuoteLabel: "كلمة رئيس المؤتمر",
    presidentQuote:
      "قال تعالى: {وَقُلِ اعْمَلُوا فَسَيَرَى اللَّهُ عَمَلَكُمْ وَرَسُولُهُ وَالْمُؤْمِنُونَ}.\\n\\nالزملاء الأعزاء، بعد ثلاث سنوات من قهر العدوان، نعود لنوقد شعلة العلم. ننحني إجلالاً لشهدائنا وأسرانا وجرحانا من الكوادر الطبية الذين جسدوا أسمى معاني التضحية. شكراً لكل يدٍ ستبني نجاح مؤتمرنا الباطني الثاني عشر.\\n\\nوفقكم الله لما يحب ويرضى.",
    presidentFooter: "رئيس المؤتمر الطبي الدولي · 2026",
    mediaCaptions: [
      { caption: "مجمع ناصر الطبي", tag: "مستشفى" },
      { caption: "حفل الافتتاح", tag: "فعاليات" },
      { caption: "ورشة عمل طبية", tag: "ورش" },
      { caption: "المتحدثون الدوليون", tag: "متحدثون" },
      { caption: "جلسة التحكيم", tag: "جلسات" },
    ],
    president: {
      name: "د. أحمد جمعة الروبي",
      role: "رئيس المؤتمر",
      title: "مدير مشفى الباطنة — استشاري الأمراض الباطنية",
      bio: "طبيب استشاري متخصص في الأمراض الباطنية، يشغل منصب مدير قسم الباطنة، وله خبرة واسعة في إدارة الحالات الطبية المعقدة والإشراف على البحث العلمي.",
      email: "rubai@medical.edu",
      phone: "+970-8-2816-1010",
      image: "/Mohamed_El_Rouby.jpg",
      expertise: ["الأمراض الباطنية", "إدارة الأقسام", "البحث العلمي"],
    },
    supervisor: {
      name: "د. عمرو الأسطل",
      role: "المشرف العام",
      title: "استشاري الأمراض الرئوية والعناية المركزة — أمريكا",
      bio: "استشاري دولي في الأمراض الرئوية والعناية المركزة، متمرس في المستشفيات الأمريكية، ويُشرف على الجانب العلمي والتنظيمي للمؤتمر.",
      email: "astal@medical.edu",
      phone: "+1-555-000-1234",
      image: "/Amr_Al_Astal.jpg",
      expertise: ["الأمراض الرئوية", "العناية المركزة", "الطب الدولي"],
    },
    committees: [
      {
        name: "اللجنة التحضيرية",
        icon: "🏗️",
        desc: "تشرف على التخطيط العام للمؤتمر وتنسيق الجدول الزمني.",
        members: ["د. محمد خطاب قنديل"],
        head: {
          name: "د. محمد خطاب قنديل",
          title: "استشاري طب الطوارئ والحالات الحرجة",
          bio: "استشاري طب الطوارئ والحالات الحرجة، يعمل حاليا في غزة وسابقا في الدوحة. حاصل على البورد العربي والزمالة البريطانية في تخصصه.",
          email: "khatab@medical.edu",
          phone: "+970-8-2816-2020",
          image: "/Mohamed_Khattab_Qandil.jpg",
          expertise: ["طب الطوارئ", "الحالات الحرجة", "التعليم الطبي"],
        },
      },
      {
        name: "اللجنة العلمية",
        icon: "🔬",
        desc: "مسؤولة عن مراجعة الأبحاث وتحديد المحاور العلمية.",
        members: ["د. محمود الشيخ علي"],
        head: {
          name: "د. محمود الشيخ علي",
          title: "استشاري الطب الباطني والمناظير",
          bio: "استشاري الطب الباطني والمناظير مع خبرة عميقة في مجاله. حاصل على الزمالة البريطانية في الطب الباطني.",
          email: "drmnali@gmail.com",
          phone: "+972-56-703-3314",
          image: "/Mahmoud_Al_Sheikh_Ali.jpg",
          expertise: ["الطب الباطني", "المناظير", "تقييم الأبحاث"],
        },
      },
      {
        name: "اللجنة الإعلامية",
        icon: "📢",
        desc: "تتولى التغطية الصحفية وإدارة منصات التواصل والموقع.",
        members: ["د. مازن سليمان صافي"],
        head: {
          name: "د. مازن سليمان صافي",
          title: "رئيس قسم الأدوية المخدرة والمراقبة — مجمع ناصر الطبي",
          bio: "رئيس قسم الأدوية المخدرة والمراقبة بمجمع ناصر الطبي، نائب مدير الصيدلية. متخصص في الإعلام الطبي وكاتب محتوى احترافي دولي.",
          email: "mazen@nasermedical.edu",
          phone: "+970-8-2822-2222",
          image: "/Mazen_Suleiman_Safi.jpg",
          expertise: [
            "الأدوية المخدرة",
            "إدارة الصيدلية",
            "الإعلام الطبي",
            "القيادة والتدريب",
          ],
        },
      },
    ],
    news: [
      {
        title: "فتح باب استقبال الأبحاث",
        date: "١ مايو ٢٠٢٦",
        icon: "📋",
        content:
          "نعلمكم أنه تم فتح باب استقبال الأبحاث العلمية ابتداءً من 1/5/2026 وحتى 30/9/2026.",
      },
      {
        title: "تأكيد مشاركة متحدثين دوليين",
        date: "٢٠ أبريل ٢٠٢٦",
        icon: "🌍",
        content:
          "يسعدنا الإعلان عن تأكيد مشاركة متحدثين دوليين من أوروبا وأمريكا.",
      },
      {
        title: "موعد المؤتمر ٤-٥ ديسمبر ٢٠٢٦",
        date: "١ أبريل ٢٠٢٦",
        icon: "📅",
        content:
          "يُعقد المؤتمر في مجمع ناصر الطبي، غزة، بتاريخ 4-5 ديسمبر 2026.",
      },
    ],
    footer: "© 2026 مؤتمر الصمود والاستدامة الطبي",
    execCommittee: "لجنة تنفيذية",
    presidentBadge: "رئيس المؤتمر",
    supervisorBadge: "مشرف عام",
    quickLinks: "روابط سريعة",
    quickLinksItems: [
      { icon: "🖥️", label: "شاشات تفاعلية", href: "/media" },
      { icon: "📄", label: "تقديم الأبحاث", href: "/participation" },
      { icon: "🌍", label: "بث مباشر", href: "/live" },
      { icon: "📋", label: "جدول المؤتمر", href: "/program" },
    ],
    edition: "• المؤتمر الثاني عشر •",
    videoLabel: "فيديو",
    noVideo: "سيتم تحميل الفيديو قريباً",
    supportingOrg: "المؤسسات الداعمة",
    registerNowTitle: "قدم بحثك الآن",
    registerNowSub: "باب التقديم مفتوح حتى 30 سبتمبر 2026",
  },
  en: {
    dir: "ltr",
    conferenceTitle: "12th International Medical Conference",
    conferenceSub:
      "Resilience & Sustainability in Emergency & Humanitarian Response",
    btnReg: "Register Now",
    btnProg: "Scientific Program",
    watchVideo: "Watch Promo Video",
    statsLbls: [
      "International Speakers",
      "Scientific Sessions",
      "Expected Attendees",
      "Participating Countries",
    ],
    newsTitle: "Conference News",
    newsTicker: "News",
    membersLbl: "Committee Head",
    expertiseLbl: "Expertise",
    galleryTitle: "Media Gallery",
    gallerySub: "Highlights from conference events",
    leadersTitle: "Conference Leadership",
    committeesTitle: "Committees",
    presidentQuoteLabel: "President's Message",
    presidentQuote:
      "It is my honor to welcome you to the International Medical Conference on Resilience and Sustainability.\\n\\nThis scientific forum embodies our noble mission: advancing healthcare standards and exchanging medical knowledge even in the most challenging of times.",
    presidentFooter:
      "Conference President · International Medical Conference 2026",
    mediaCaptions: [
      { caption: "Nasser Medical Complex", tag: "Hospital" },
      { caption: "Opening Ceremony", tag: "Events" },
      { caption: "Medical Workshop", tag: "Workshops" },
      { caption: "Int'l Speakers", tag: "Speakers" },
      { caption: "Review Session", tag: "Sessions" },
    ],
    president: {
      name: "Dr. Ahmed Jumaa Al-Rubai",
      role: "Conference President",
      title: "Head of Internal Medicine — Consultant Internist",
      bio: "Consultant specialist in internal medicine, serving as Head of the Internal Medicine Department, with extensive experience in complex case management and scientific research oversight.",
      email: "rubai@medical.edu",
      phone: "+970-8-2816-1010",
      image: "/Mohamed_El_Rouby.jpg",
      expertise: [
        "Internal Medicine",
        "Department Management",
        "Scientific Research",
      ],
    },
    supervisor: {
      name: "Dr. Omar Al-Astal",
      role: "General Supervisor",
      title: "Pulmonology & Critical Care — USA",
      bio: "International consultant in pulmonology and critical care, experienced in American hospitals, overseeing the scientific and organizational aspects of the conference.",
      email: "astal@medical.edu",
      phone: "+1-555-000-1234",
      image: "/Amr_Al_Astal.jpg",
      expertise: ["Pulmonology", "Critical Care", "Int'l Medicine"],
    },
    committees: [
      {
        name: "Preparatory Committee",
        icon: "🏗️",
        desc: "Oversees general planning and timeline coordination.",
        members: ["Dr. Mohammad Qandil"],
        head: {
          name: "Dr. Mohammed Khatab Qandil",
          title: "Emergency Medicine & Critical Care Consultant",
          bio: "Consultant in Emergency Medicine and Critical Care, currently working in Gaza and previously in Doha. Holds the Arab Board and British Fellowship in his specialty.",
          email: "khatab@medical.edu",
          phone: "+970-8-2816-2020",
          image: "/Mohamed_Khattab_Qandil.jpg",
          expertise: [
            "Emergency Medicine",
            "Critical Care",
            "Medical Education",
          ],
        },
      },
      {
        name: "Scientific Committee",
        icon: "🔬",
        desc: "Reviews abstracts, sets themes, and selects speakers.",
        members: ["Dr. Mahmoud Al-Sheikh Ali"],
        head: {
          name: "Dr. Mahmoud Al-Sheikh Ali",
          title: "Consultant Internal Medicine & Endoscopy",
          bio: "Consultant in Internal Medicine and Endoscopy. Holds the British Fellowship in Internal Medicine. Head of the Scientific Committee.",
          email: "sheikh@medical.edu",
          phone: "+970-8-2816-3030",
          image: "/Mahmoud_Al_Sheikh_Ali.jpg",
          expertise: ["Internal Medicine", "Endoscopy", "Research Evaluation"],
        },
      },
      {
        name: "Media Committee",
        icon: "📢",
        desc: "Handles press coverage and social media management.",
        members: ["Dr. Mazen Soliman Safi"],
        head: {
          name: "Dr. Mazen Soliman Safi",
          title:
            "Head of Controlled Medications Department — Nasser Medical Complex",
          bio: "Head of Controlled Medications at Nasser Medical Complex. Specialist in medical media and professional content writer.",
          email: "mazen@nasermedical.edu",
          phone: "+970-8-2822-2222",
          image: "/Mazen_Suleiman_Safi.jpg",
          expertise: [
            "Controlled Medications",
            "Pharmacy Management",
            "Medical Media",
            "Leadership & Training",
          ],
        },
      },
    ],
    news: [
      {
        title: "Abstract Submission Open",
        date: "May 1, 2026",
        icon: "📋",
        content: "Abstract submission is open from May 1st to June 30th, 2026.",
      },
      {
        title: "Int'l Speakers Confirmed",
        date: "Apr 20, 2026",
        icon: "🌍",
        content:
          "International speakers from Europe and USA have been confirmed.",
      },
      {
        title: "Conference: Dec 4–5, 2026",
        date: "Apr 1, 2026",
        icon: "📅",
        content: "The conference will be held at Nasser Medical Complex, Gaza.",
      },
    ],
    footer: "© 2026 Medical Resilience & Sustainability Conference",
    execCommittee: "Executive Committee",
    presidentBadge: "Conference President",
    supervisorBadge: "General Supervisor",
    quickLinks: "Quick Links",
    quickLinksItems: [
      { icon: "🖥️", label: "Interactive Screens", href: "/media" },
      { icon: "📄", label: "Research Submission", href: "/participation" },
      { icon: "🌍", label: "Live Stream", href: "/live" },
      { icon: "📋", label: "Schedule", href: "/program" },
    ],
    edition: "• 12th EDITION •",
    videoLabel: "Video",
    noVideo: "Video will be available soon",
    supportingOrg: "Supporting Organization",
    registerNowTitle: "Submit Your Research",
    registerNowSub: "Submission open until Sep 30, 2026",
  },
};
